<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>checkEligibility</name>
  <uuid>176b664b-8f09-4e50-b299-90e7129bfce9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if salary is at least 25000 
and creditScore is at least 700 and less than 1000 then 
	set decision to true ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
